/*    
 Copyright (C) Atiyah Elsheikh (Atiyah.Elsheikh@ait.ac.at,a.m.g.Elsheikh@gmail.com) 2010-2013, AIT Austrian Institute of Technology GmbH

    This file is part of the software DecTrees and InteractiveMneus

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>
*/

#include "myconstants.h"

pair<string,double> myconstants::KEYS_DEF_VAL[NUM_SIM_KEYS] = { 
    pair<string,double>("StartTime",0),
    pair<string,double>("StopTime",1),
    pair<string,double>("Increment",0.1),
    pair<string,double>("nInterval",0),
    pair<string,double>("Tolerance",1.0E-8),
    pair<string,double>("MaxFixedStep",0),
    pair<string,double>("Algorithm",8)
};
 

const string myconstants::OCTAVE_TEMP_DIR      = "oct.tmp" ;
const string myconstants::OCTAVE_PAR_FILE      = "p.txt";
const string myconstants::OCTAVE_PARNAMES_FILE = "pnames.txt"; 
const string myconstants::OCTAVE_X0_FILE       = "x0.txt"; 
const string myconstants::OCTAVE_X0NAMES_FILE  = "x0names.txt";


const string myconstants::LOAD_DSIN_SHELL      = "loaddsin.ksh"  ;
const string myconstants::UPDATE_DSIN_SHELL    = "updateDsin.sh" ;


const string myconstants::DYMOSIM              = "dymosim";   // Excutable generated from dymola
const string myconstants::DSRES_FILE           = "dsres.txt"; // Output file generated by dymosim
const string myconstants::DSINP_FILE           = "dsin.txt";  // input file generated by dymosim
const string myconstants::DSINP_DIR            = "dsin";     // directory where temp input files are located
const string myconstants::DSRES_DIR            = "dsres";    // ...

const int myconstants::MAX_BUFF_LEN  = 100; 
